In [1]:
import io
import sqlite3
import pandas as pd

import matplotlib as plt

In [4]:
conn = sqlite3.connect('tp1.db')
cursor = conn.cursor()

f = io.open('despesas_publicas_tp1.sql', 'r', encoding='ISO-8859-1')
sql = f.read()
cursor.executescript(sql)

# Questões: 1 2   4 5   7 9 / 
#             2 3   5 6 7 9

In [76]:
# df = pd.read_sql_query('', conn)
# df

#### 1. Liste todos os códigos e nomes de subfunções da função que possui o maior número de subfunções.

In [ ]:
df = pd.read_sql_query('SELECT A.COD_SUBFUNCAO, A.NOME_SUBFUNCAO FROM SUBFUNCAO AS A '+
                       'INNER JOIN (SELECT COD_SUBFUNCAO FROM DETALHAMENTO_FUNCAO WHERE COD_FUNCAO = ('+
                           'SELECT COD_FUNCAO FROM ('+
                               'SELECT COD_FUNCAO, MAX(Y.SUB) FROM ( '+
                                   'SELECT COD_FUNCAO, COUNT(COD_SUBFUNCAO) as SUB '+
                                   'FROM DETALHAMENTO_FUNCAO '+
                                   'GROUP BY COD_FUNCAO' +
                                ') Y '+
                          ')'+
                       ')) AS X ON A.COD_SUBFUNCAO = X.COD_SUBFUNCAO', conn)
df

#### 2. Liste o valor total de despesas públicas por função (nome) e subfunção(nome), apenas nos casos em que esse valor total excedeu 200 mil reais.

In [ ]:
df = pd.read_sql_query('SELECT FUNC.NOME_FUNCAO, SUBFUNC.NOME_SUBFUNCAO, CODS.VALOR_DESPESA FROM FUNCAO AS FUNC, SUBFUNCAO AS SUBFUNC INNER JOIN'+
                       '(SELECT * FROM DETALHAMENTO_FUNCAO AS DETALHAMENTO INNER JOIN '+
                       '(SELECT * FROM DESPESA_PUBLICA WHERE VALOR_DESPESA > 200000) AS DESPESA '+
                       'ON DETALHAMENTO.COD_DETALHAMENTO = DESPESA.COD_DETALHAMENTO) AS CODS '+
                       'ON FUNC.COD_FUNCAO = CODS.COD_FUNCAO AND SUBFUNC.COD_SUBFUNCAO = CODS.COD_SUBFUNCAO', conn)
df

#### ❌ 3.Liste todos os nomes dos órgaos e o valor das despesas totais no ano de 2018 para os mesmos, ordenando de forma decrescente pelo valor.

In [ ]:
df = pd.read_sql_query('SELECT ORGAO.NOME_ORGAO, SUM(DESPESA.VALOR_DESPESA) TOTAL_DESPESA FROM ORGAO INNER JOIN '+
                       '(SELECT * FROM DESPESA_PUBLICA WHERE ANO_DESPESA = 2018) AS DESPESA '+
                       'ON ORGAO.COD_ORGAO = DESPESA.COD_ORGAO GROUP BY NOME_ORGAO ORDER BY TOTAL_DESPESA DESC', conn)
df

#### 4. Liste o mês e ano, modalidade, programa de governo e valor de todas as despesas do órgão Ministério da Fazenda no primeiro semestre de 2018.

In [75]:
df = pd.read_sql_query('SELECT DESPESA.MES_DESPESA, DESPESA.ANO_DESPESA, DESPESA.MODALIDADE_DESPESA, PROGRAMA.NOME_PROGRAMA_GOVERNO, DESPESA.VALOR_DESPESA TOTAL_DESPESA FROM PROGRAMA_GOVERNO AS PROGRAMA INNER JOIN '+
                       '(SELECT * FROM DESPESA_PUBLICA AS DESPESA INNER JOIN '+
                       '(SELECT * FROM ORGAO WHERE NOME_ORGAO = "Ministério da Fazenda" ) AS ORGAO '+
                       'ON DESPESA.COD_ORGAO = ORGAO.COD_ORGAO) AS DESPESA WHERE DESPESA.MES_DESPESA < 7', conn)
df

,MES_DESPESA,ANO_DESPESA,MODALIDADE_DESPESA,NOME_PROGRAMA_GOVERNO,TOTAL_DESPESA
0,4,2018,Reserva de Contingência,VIVER SEM LIMITE,0
1,1,2018,Reserva de Contingência,VIVER SEM LIMITE,0
2,2,2018,Reserva de Contingência,VIVER SEM LIMITE,0
3,3,2018,Reserva de Contingência,VIVER SEM LIMITE,0
4,4,2018,Reserva de Contingência,VIVER SEM LIMITE,0
5,5,2018,Reserva de Contingência,VIVER SEM LIMITE,0
6,6,2018,Reserva de Contingência,VIVER SEM LIMITE,0
7,4,2018,Reserva de Contingência,SOS EMERGENCIA,0
8,1,2018,Reserva de Contingência,SOS EMERGENCIA,0
9,2,2018,Reserva de Contingência,SOS EMERGENCIA,0
10,3,2018,Reserva de Contingência,SOS EMERGENCIA,0
11,4,2018,Reserva de Contingência,SOS EMERGENCIA,0
12,5,2018,Reserva de Contingência,SOS EMERGENCIA,0
13,6,2018,Reserva de Contingência,SOS EMERGENCIA,0
14,4,2018,Reserva de Contingência,MELHOR EM CASA,0
15,1,2018,Reserva de Contingência,MELHOR EM CASA,0
16,2,2018,Reserva de Contingência,MELHOR EM CASA,0
17,3,2018,Reserva de Contingência,MELHOR EM CASA,0
18,4,2018,Reserva de Contingência,MELHOR EM CASA,0
19,5,2018,Reserva de Contingência,MELHOR EM CASA,0
20,6,2018,Reserva de Contingência,MELHOR EM CASA,0
21,4,2018,Reserva de Contingência,UBS,0
22,1,2018,Reserva de Contingência,UBS,0
23,2,2018,Reserva de Contingência,UBS,0
24,3,2018,Reserva de Contingência,UBS,0
25,4,2018,Reserva de Contingência,UBS,0
26,5,2018,Reserva de Contingência,UBS,0
27,6,2018,Reserva de Contingência,UBS,0
28,4,2018,Reserva de Contingência,"UPA (INVESTIMENTO, CUSTEIO E COMPLEXO DE REGUL...",0
29,1,2018,Reserva de Contingência,"UPA (INVESTIMENTO, CUSTEIO E COMPLEXO DE REGUL...",0
...,...,...,...,...,...
159,5,2018,Reserva de Contingência,ENAFRON,0
160,6,2018,Reserva de Contingência,ENAFRON,0
161,4,2018,Reserva de Contingência,VIOLENCIA NO TRANSITO,0
162,1,2018,Reserva de Contingência,VIOLENCIA NO TRANSITO,0
163,2,2018,Reserva de Contingência,VIOLENCIA NO TRANSITO,0
164,3,2018,Reserva de Contingência,VIOLENCIA NO TRANSITO,0
165,4,2018,Reserva de Contingência,VIOLENCIA NO TRANSITO,0
166,5,2018,Reserva de Contingência,VIOLENCIA NO TRANSITO,0
167,6,2018,Reserva de Contingência,VIOLENCIA NO TRANSITO,0
168,4,2018,Reserva de Contingência,SEGURO RURAL PRIVADO,0
169,1,2018,Reserva de Contingência,SEGURO RURAL PRIVADO,0
170,2,2018,Reserva de Contingência,SEGURO RURAL PRIVADO,0
171,3,2018,Reserva de Contingência,SEGURO RURAL PRIVADO,0
172,4,2018,Reserva de Contingência,SEGURO RURAL PRIVADO,0
173,5,2018,Reserva de Contingência,SEGURO RURAL PRIVADO,0
174,6,2018,Reserva de Contingência,SEGURO RURAL PRIVADO,0
175,4,2018,Reserva de Contingência,PROGRAMA NACIONAL DE MELHORIA DE ACESSO E QUAL...,0
176,1,2018,Reserva de Contingência,PROGRAMA NACIONAL DE MELHORIA DE ACESSO E QUAL...,0
177,2,2018,Reserva de Contingência,PROGRAMA NACIONAL DE MELHORIA DE ACESSO E QUAL...,0
178,3,2018,Reserva de Contingência,PROGRAMA NACIONAL DE MELHORIA DE ACESSO E QUAL...,0
179,4,2018,Reserva de Contingência,PROGRAMA NACIONAL DE MELHORIA DE ACESSO E QUAL...,0
180,5,2018,Reserva de Contingência,PROGRAMA NACIONAL DE MELHORIA DE ACESSO E QUAL...,0
181,6,2018,Reserva de Contingência,PROGRAMA NACIONAL DE MELHORIA DE ACESSO E QUAL...,0
182,4,2018,Reserva de Contingência,MAIS MEDICOS,0
183,1,2018,Reserva de Contingência,MAIS MEDICOS,0
184,2,2018,Reserva de Contingência,MAIS MEDICOS,0
185,3,2018,Reserva de Contingência,MAIS MEDICOS,0
186,4,2018,Reserva de Contingência,MAIS MEDICOS,0
187,5,2018,Reserva de Contingência,MAIS MEDICOS,0
188,6,2018,Reserva de Contingência,MAIS MEDICOS,0

#### 5. Liste o código e nome dos programas de governo que possuíram os 3 maiores valores de despesas totais na função de educação durante o ano de 2018.

In [61]:
df = pd.read_sql_query('SELECT DESPESA.COD_PROGRAMA_GOVERNO, DESPESA.NOME_PROGRAMA_GOVERNO FROM '+
                       '(SELECT * FROM PROGRAMA_GOVERNO AS PROGRAMA INNER JOIN'+
                       '(SELECT * FROM DESPESA_PUBLICA AS DESPESA INNER JOIN'+
                       '(SELECT * FROM DETALHAMENTO_FUNCAO WHERE COD_FUNCAO ='+
                       '(SELECT COD_FUNCAO FROM FUNCAO WHERE NOME_FUNCAO = "Educação" )) AS EDU '+
                       'ON DESPESA.COD_DETALHAMENTO = EDU.COD_DETALHAMENTO) AS DESPESA '+
                       'ON PROGRAMA.COD_PROGRAMA_GOVERNO = DESPESA.COD_PROGRAMA_GOVERNO) AS DESPESA '+
                       'GROUP BY DESPESA.COD_PROGRAMA_GOVERNO ORDER BY SUM(VALOR_DESPESA) DESC LIMIT 3', conn)
df

   COD_PROGRAMA_GOVERNO NOME_PROGRAMA_GOVERNO
0                    11                  ENEM
1                    14              PRONATEC
2                    35          MAIS MEDICOS

#### ❌ 6. Liste todos os nomes de funções e subfunções das despesas públicas do terceiro trimestre de 2018 e seus respectivos valores totais, apenas para o programa MAIS MEDICOS.

In [74]:
df = pd.read_sql_query('SELECT NOME_FUNCAO FUNCAO, NOME_SUBFUNCAO SUBFUNCAO, SUM(VALOR_DESPESA) TOTAL_DESPESA FROM FUNCAO, SUBFUNCAO INNER JOIN'+
                       '(SELECT * FROM DETALHAMENTO_FUNCAO INNER JOIN'+
                       '(SELECT * FROM DESPESA_PUBLICA INNER JOIN'+
                       '(SELECT * FROM PROGRAMA_GOVERNO WHERE NOME_PROGRAMA_GOVERNO = "MAIS MEDICOS" ) AS MED '+
                       'ON MED.COD_PROGRAMA_GOVERNO = DESPESA_PUBLICA.COD_PROGRAMA_GOVERNO) AS DESPESAS '+
                       'ON DETALHAMENTO_FUNCAO.COD_DETALHAMENTO = DESPESAS.COD_DETALHAMENTO) AS DET '+
                       'ON FUNCAO.COD_FUNCAO = DET.COD_FUNCAO AND SUBFUNCAO.COD_SUBFUNCAO = DET.COD_SUBFUNCAO '+
                       'WHERE MES_DESPESA >=7 AND MES_DESPESA <=9 AND ANO_DESPESA = 2018 GROUP BY FUNCAO', conn)
df

            FUNCAO            SUBFUNCAO  TOTAL_DESPESA
0  Defesa nacional  Administração geral              0
1         Educação      Ensino superior           2400
2            Saúde       Atenção básica          11000